[package]
name = "Aether"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
glib = "0.20"
gio = "0.20"
gtk4 = "0.9"
gtk4-layer-shell = "0.4"
webkit6 = "0.4"
chrono = "0.4"
hyprland = "0.4.0-beta.1"
battery = "0.7.8"
